baseURL = 'https://jiangxingye.github.io/'
locale = 'zh-CN'
title = "jiangxingye's blog"
theme = ["FixIt"]
enableGitInfo = false

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":gitLastMod", ":getGitLastMod"]

[params]
  comments = true
  default_theme = "auto"
  word_count = true
  reading_time = true
  show_lastmod = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  env = "production"
  date_format = "2006-01-02"

[params.busuanzi]
  enable = true
  source = "https://vercount.one/js"
  site_views = true
  page_views = true

[params.comment]
  enable = true

[params.comment.gitalk]
  enable = true
  owner = "jiangxingye"
  repo = "jiangxingye-comments"
  client_id = ""
  client_secret = ""

[params.author]
  name = "jiangxingye"
  email = "jiangxingye@outlook.com"
  link = "https://jiangxingye.github.io/"

[params.social]
  GitHub = "https://github.com/jiangxingye"
  Weibo = "https://weibo.com/jiangxingye"
  QQ = "http://wpa.qq.com/msgrd?v=3&uin=174762929&site=qq&menu=yes"
  Email = "mailto:jiangxingye@outlook.com"

[params.home.profile]
  enable = true
  avatar_url = "/img/avatar.jpg"
  title = "jiangxingye"
  subtitle = "不是啥程序员，自己利用空闲时间写点东西，有技术，也有一些岁月感悟。毕业于吉林省万顺中学，目前在做IT智能和硬件服务器这个行当。联系方式 QQ：174762929，Wechat：jiangxingye，邮箱：jiangxingye@outlook.com"
  typeit = false
  social = true

[params.custom_partials]
  footer = ["custom/footer.html"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "about/"
    weight = 10
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "archives/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "tags/"
    weight = 30
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "categories/"
    weight = 40
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "search/"
    weight = 50

[outputs]
  home = ["HTML", "RSS", "ARCHIVES", "SEARCH", "MANIFEST"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[minify]
  disableJS = true
